# Generated by Django 3.1.7 on 2021-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20210407_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price_discounted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
