# Generated by Django 3.1.7 on 2021-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20210407_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
